name: CI

on:
  push:
  pull_request:

jobs:
  rust:
    name: Rust workspace
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Check examples
        run: cargo check --workspace --examples

      - name: Test workspace
        run: cargo test --workspace

      - name: Clippy examples and all targets
        run: cargo clippy --workspace --examples --all-targets -- -D warnings

      - name: Check no default features
        run: cargo check --workspace --no-default-features

      - name: Check all features examples
        run: cargo check --workspace --all-features --examples
